### ISSUE TITLE
Deploying an app that uses django-json-rpc

### ISSUE THREAD

**Issue by miclovich** [samuraisam/django-json-rpc#14]
Hello,
I've tried working with your package (json-rpc for django)... I however can't get my json rpc calls to work on a live server...
It works okay with my localhost... on the local host I get the following json scripts after sending a HTTP GET (typing inside of my browser)
i.e.
http://localhost:8000/json/testapp.tagText?text=I want to eat some great apples

returns this tagged json object:

{"id": "jsonrpc", "version": "1.1", "result": "{\"tagged\": [\"apples\"]}"}

a @jsonrpc_method, I wrote, is used to extract tags from text sent to it by GET

The errors:
This is what I get when I take this django up live (on the web under mod_wsgi/apache... which has all dependencies installed)

{"error": {"executable": "/usr/bin/python", "code": -32600, "name": "InvalidRequestError", "message": "InvalidRequestError: The method you are trying to access is not availble by GET requests", "data": null, "stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.6/dist-packages/django_json_rpc-0.6.1-py2.6.egg/jsonrpc/site.py\", line 183, in dispatch\n    raise InvalidRequestError('The method you are trying to access is '\nInvalidRequestError\n"}, "id": null, "result": null}

What is the solution for this? Has any one tried having an app that emits/spits out json objects running on SliceHost, for example?
regards & thnx

**Comment by AndreiMisca** [comment]
I have the same problem in Django 1.10 in the production server , in my machine it all works great. 
Any help ?
