### ISSUE TITLE
upload the new version to PyPi 0.6.2

### ISSUE THREAD

**Issue by kobymeir** [samuraisam/django-json-rpc#57]
Hi there,
I see that the code in the git is newer 0.6.2 than the code in PyPi 0.6.1 and i need it to support Django 1.7

could you please upload the new version to PyPi?

I usually don't like using packages from the git repositories.

Thanks :)
Koby

**Comment by samuraisam** [comment]
Done!

**Comment by kobymeir** [comment]
Thanks :)
