### ISSUE TITLE
Import error with python 3

### ISSUE THREAD

**Issue by olymk2** [samuraisam/django-json-rpc#69]
I have a django app setup in a virtualenv, i am currently porting this to python 3, I am hitting issues with django-json-rpc import.

basically i am getting the issue below, running python interactively I can see that indeed _json does not exist how ever i can change it to from json import dumps.

    /src/django-json-rpc/jsonrpc/views.py", line 1, in <module>
    from _json import dumps
    ImportError: cannot import name 'dumps' ```

is this a known issue or am I missing a requirement ?

**Comment by samuraisam** [comment]
What version of Python 3 are you using? We might have to make it `from ._json import dumps`

**Comment by olymk2** [comment]
default on ubuntu 15.04

python3 --version
Python 3.4.3

**Comment by olymk2** [comment]
worth noting I just deleted the _ and everything seemed to be working, though I have not thoroughly tested this yet but it got my django app running.

**Comment by alex-moon** [comment]
It's a name clash:

```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _json
>>> _json
<module '_json' from '/usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so'>
>>>
```

A quick Google suggests that's an Android library. If it's installed outside the site packages it'll conflict. Simple `from . import _json` should do the trick.

**Comment by samuraisam** [comment]
Derp, sorry for not noticing this. Will from ._json affect earlier python versions (eg 2.6?)

**Comment by samuraisam** [comment]
Meh, I just made it an absolute import. Will merge in and update PyPI

**Comment by samuraisam** [comment]
Ok, 0.7.1 is out which fixes this issue
