### ISSUE TITLE
Set default standard's version to 2.0

### ISSUE THREAD

**Issue by yura-shutkin** [samuraisam/django-json-rpc#82]
Good day,
Is is possible to set by config or by some other way the default version of jsonrpc to 2.0 if version not specified at query (HTTPRequest.body)

**Comment by samuraisam** [comment]
I'm not sure what this would look like. We automatically detect based on the contents of the request.

**Comment by yura-shutkin** [comment]
Thank you for quick answer. About my trouble.
There is only  json-rpc  module and django 1.9.3. Code from README.md
curl -D- --header "Authorization: Bearer my_private_token" -H "Content-Type: application/json" -X POST -d '{"method": "sayHello", "params":{"name": "yshutkin"}, "id": 1}' http://localhost:8080/api/v1/

if i do not send version i got answer:
{"result": "Hello name", "id": 1, "error": null}

But if query looks like:
curl -D- --header "Authorization: Bearer my_private_token" -H "Content-Type: application/json" -X POST -d '{"jsonrpc": "2.0", "method": "sayHello", "params":{"name": "yshutkin"}, "id": 1}' http://localhost:8080/api/v1/
I've got:
{"jsonrpc": "2.0", "result": "Hello yshutkin", "id": 1}

**Comment by samuraisam** [comment]
Sorry, it's been a while since I've used JSON-RPC - is it standards compliant to default to version 2.0?

**Comment by yura-shutkin** [comment]
if i do understand correctly, query without jsonrpc is not a standard to omit "jsonrpc": "2.0" (http://www.jsonrpc.org/specification#request_object).
But my client do want to send queries without this part.

**Comment by samuraisam** [comment]
What client are you using? Can your client be updated?

**Comment by yura-shutkin** [comment]
Good day,
Sorry i couldn't answer for a few days. Sorry for misunderstanding "client" == Boss or Customer.
I do looking for pre processing all requests. So this issue may be closed.
Thank you for your time.
